### ISSUE TITLE
Websocket Event Listener doesn't catch entry sensors firing

### ISSUE THREAD

**Issue by LordFransie** [bachya/simplisafe-python#118]
**Describe the bug**
When a websocket is open there is no detection of entry sensors opening or closing.

**To Reproduce**
1. Start a websession (ie: test_websocket)
2. Trigger an entry sensor
3. No message shows up

**Expected behavior**
I expected the entry sensor to show up, instead it shows nothing. I have successfully displayed other events such as arming and disarming.

**Comment by bachya** [comment]
Unfortunately, generalized sensor events (such an entry sensor opening/closing) don’t propagate down the websocket. The only exceptions are events that would cause an entry delay or trigger an alarm. This is something SimpliSafe owns and cannot be fixed in this library.

If you still think there’s an event that should be captured, but isn’t, you’ll find evidence of it in the `Timeline` page of the SimpliSafe web and mobile apps. Please post a screenshot of those events here and we’ll reopen this issue.
