### ISSUE TITLE
error when creating  dev environment

### ISSUE THREAD

**Issue by maxcli** [bachya/simplisafe-python#589]
when running  script/setup   :
Failed building wheel for cryptography
 command failed: 'rustc': No such file or directory (os error 2)

**To Reproduce**
run   script/setup
following this guide https://simplisafe-python.readthedocs.io/en/latest/usage.html

I am using   Raspberry PI Raspbian 11
Python and Python3 are 3.9.2

**Additional context**
I tried various steps below but no luck :
 
 -Raspberry PI update :sudo apt update,sudo apt full-upgrade, sudo reboot
 - reimage the OS  Raspbian 11
-run  shell commands manually, and got error : poetry install
Poetry could not find a pyproject.toml file in /home/pi or its parents

-clearing pip cache sudo rm  -rf /root/.cache/pip
 
-  setting dns-nameservers 8.8.4.4 8.8.8.8

Any suggestions ?

**Comment by bachya** [comment]
The dev environment installs the [`cryptography`](https://cryptography.io/en/latest/) package, which introduced Rust as a build-time dependency in version 3.4. By default, `pip` will attempt to download pre-built wheels for a platform; in your case (either ARMv6, ARMv7, or ARM64, depending on the processor architecture of your Raspberry Pi), `pip` can't find a pre-built `cryptography` wheel, attempts to build one from scratch, and fails because it can't find a Rust compiler.

The most straightforward thing to try is to [install a Rust compiler on your Pi](https://linuxhint.com/install-rust-raspberry-pi/), then run `script/setup`.

**Comment by maxcli** [comment]
I really want to use your SSafe API  

I tried the curl command  on a clean RPI image
but  rustc --version  <--   command failed: 'rustc':

my path contains /home/pi/.cargo/bin:  , and I clearly see rustc in the bin folder

Any other tips?

**Comment by bachya** [comment]
Are you attempting just to use this library, or develop code for it? If it's the former, you can simply install it via `pip`:

```
$ pip install simplisafe-python
```

The Rust runtime is only required when developing code _for_ `simplisafe-python`.

**Comment by maxcli** [comment]
I just want to use your library.   
I got the code=xxx variable. 
Thanks.
